/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.view.screens.create;

import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.controller.FornecedorController;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.controller.ImpressoraController;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.controller.ModeloImpressoraController;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.factory.SessionStorageSingleton;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.DataResponseModel;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.entities.Fornecedor;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.entities.Impressora;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.entities.ModeloImpressora;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.utils.ComboBoxItem;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.utils.DefaultMessages;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.view.screens.template.FrMain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author misael
 */
public class CreateImpressoraScreen extends javax.swing.JDialog {
    private ImpressoraController impressoraController = new ImpressoraController();
    private ModeloImpressoraController modeloImpressoraController = new ModeloImpressoraController();
    private FornecedorController fornecedorController = new FornecedorController();
    private List<ModeloImpressora> modeloImpressoraLista = new ArrayList<>();
    private List<Fornecedor> fornecedorLista = new ArrayList<>();

    private Long modeloImpressoraId = 0L;
    private Long fornecedorId = 0L;
    /**
     * Creates new form CreateImpressoraScreen
     */
    public CreateImpressoraScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.buscarModeloImpressora();
        this.buscarFornecedores();
        this.preencherCampos();
        this.iniciarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcbModeloImpressora = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbFornecedores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txCdSerie = new javax.swing.JTextField();
        txCdBarras = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbInAlugada = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jcbInDisponivel = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("DETALHES IMPRESSORA");

        jcbModeloImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbModeloImpressoraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Modelo: ");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Fornecedor:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("N° Série");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("Cod Barras:");

        jcbInAlugada.setText("Impressora alugada?");
        jcbInAlugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInAlugadaActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Cancelar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jcbInDisponivel.setText("Impressora disponivel?");
        jcbInDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInDisponivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcbModeloImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbInDisponivel)
                            .addComponent(txCdSerie))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbInAlugada)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcbFornecedores, 0, 300, Short.MAX_VALUE)
                        .addComponent(txCdBarras)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbModeloImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcbFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txCdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txCdBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbInAlugada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbInDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(304, 304, 304))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbInAlugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInAlugadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbInAlugadaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        HashMap<String,String> dados = this.pegarDadosPreenchidos();
        System.out.println(dados);
        DataResponseModel<Impressora> resp = this.impressoraController.save(dados);
        FrMain.exibirPopUp(resp.getMessage());
        if(resp.isSuccess()) {
           this.dispose();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        HashMap<String, String> dados = this.pegarDadosPreenchidos();
        SessionStorageSingleton.set("cadastroImpressora", dados);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jcbModeloImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbModeloImpressoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbModeloImpressoraActionPerformed

    private void jcbInDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInDisponivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbInDisponivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateImpressoraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateImpressoraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateImpressoraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateImpressoraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateImpressoraScreen dialog = new CreateImpressoraScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void buscarModeloImpressora(){
        DataResponseModel<List<ModeloImpressora>> resp = this.modeloImpressoraController.findAll();
        if(!resp.isSuccess()){
            FrMain.exibirPopUp(resp.getMessage());
            this.dispose();
            return;
        }
        this.modeloImpressoraLista = resp.getData();
    }

    private void buscarFornecedores(){
        DataResponseModel<List<Fornecedor>> resp = this.fornecedorController.findAll();
        if(!resp.isSuccess()){
            FrMain.exibirPopUp(resp.getMessage());
            this.dispose();
            return;
        }
        this.fornecedorLista = resp.getData();
    }
    private void iniciarComboBox(){
        if(Objects.isNull(this.modeloImpressoraLista) || Objects.isNull(this.fornecedorLista) || this.modeloImpressoraLista.isEmpty() || this.fornecedorLista.isEmpty()) {
            FrMain.exibirPopUp(DefaultMessages.ERRO_DADOS_NAO_ENCOTRADO.getMessage());
            this.dispose();
            return;
        }
        int modeloIndex = 0;
        for(int i =0;i<this.modeloImpressoraLista.size();i++){
            ModeloImpressora modeloImpressora = this.modeloImpressoraLista.get(i);
            this.jcbModeloImpressora.addItem(new ComboBoxItem(
                    String.valueOf(modeloImpressora.getId()),
                    String.format("%d- %s: %s",
                            modeloImpressora.getId(),
                            modeloImpressora.getMarcaImpressora().getNmMarca(),
                            modeloImpressora.getNmModeloImpressora()
                    )
            ));
            if(modeloImpressora.getId().equals(this.modeloImpressoraId)){
                modeloIndex = i;
            }
        }
        this.jcbModeloImpressora.setSelectedIndex(modeloIndex);

        int fornecedorIndex = 0;
        for(int i =0;i<this.fornecedorLista.size();i++){
            Fornecedor fornecedor = this.fornecedorLista.get(i);
            this.jcbFornecedores.addItem(new ComboBoxItem(String.valueOf(fornecedor.getId()),fornecedor.getNmFornecedor()));
            if(fornecedor.getId().equals(this.fornecedorId)){
                fornecedorIndex = i;
            }
        }
        this.jcbFornecedores.setSelectedIndex(fornecedorIndex);

    }
    private void preencherCampos(){
        try {

            Object dados = SessionStorageSingleton.get("cadastroImpressora");
            if (dados instanceof HashMap) {
                HashMap<String, String> mapa = (HashMap<String, String>) dados;
                this.fornecedorId = Long.valueOf(mapa.get("idFornecedorImpressora"));
                this.modeloImpressoraId = Long.valueOf(mapa.get("idModeloImpressora"));
                String cdBarra = mapa.get("cdBarrasImpressora");
                String cdSerie = mapa.get("cdSerieImpressora");
                
                boolean disponivel = Boolean.parseBoolean(mapa.get("inImpressoraDisponivel"));
                boolean alugada = Boolean.parseBoolean(mapa.get("inImpressoraAlugada"));
                
                this.txCdBarras.setText(cdBarra);
                this.txCdSerie.setText(cdSerie);
                this.jcbInDisponivel.setSelected(disponivel);                
                this.jcbInAlugada.setSelected(alugada);

            }
        }catch (Exception e){
            System.out.println(e.getMessage());
            return;
        }
    }

    private HashMap<String,String> pegarDadosPreenchidos(){
        HashMap<String,String> map = new HashMap<>();
        map.put("idFornecedorImpressora", String.valueOf(this.fornecedorLista.get(this.jcbFornecedores.getSelectedIndex()).getId()));
        map.put("idModeloImpressora", String.valueOf(this.modeloImpressoraLista.get(this.jcbModeloImpressora.getSelectedIndex()).getId()));
        map.put("cdBarrasImpressora",this.txCdBarras.getText());
        map.put("cdSerieImpressora",this.txCdSerie.getText());
        map.put("inImpressoraDisponivel", String.valueOf(this.jcbInDisponivel.isSelected()));        
        map.put("inImpressoraAlugada", String.valueOf(this.jcbInAlugada.isSelected()));

        return map;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<ComboBoxItem> jcbFornecedores;
    private javax.swing.JCheckBox jcbInAlugada;
    private javax.swing.JCheckBox jcbInDisponivel;
    private javax.swing.JComboBox<ComboBoxItem> jcbModeloImpressora;
    private javax.swing.JTextField txCdBarras;
    private javax.swing.JTextField txCdSerie;
    // End of variables declaration//GEN-END:variables
}
