/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.view.screens.create;

import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.controller.FornecedorController;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.controller.ImpressoraController;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.controller.ModeloImpressoraController;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.factory.SessionStorageSingleton;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.DataResponseModel;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.entities.Cliente;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.entities.Fornecedor;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.entities.Impressora;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.model.entities.ModeloImpressora;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.utils.ComboBoxItem;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.utils.DefaultMessages;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.view.screens.read.ReadImpressoraScreen;
import br.edu.lps.misael_otavio.sistema_gerenciamento_aluguel_impressoras.view.screens.template.FrMain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author misael
 */
public class CreateCotacaoScreen extends javax.swing.JDialog {
    private Cliente cliente;
    /**
     * Creates new form CreateImpressoraScreen
     */
    public CreateCotacaoScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    public CreateCotacaoScreen(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.cliente = cliente;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCadEnderecos = new javax.swing.JButton();
        btnCadGpImpressora = new javax.swing.JButton();
        btnCadServAdicionais = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jcbEndereco = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jcbGrupoImpressora = new javax.swing.JCheckBox();
        jcbServicosAdicionais = new javax.swing.JCheckBox();
        jbcFormaPagamento = new javax.swing.JCheckBox();
        jcbDadosPagamento = new javax.swing.JCheckBox();
        jcbParcelamento = new javax.swing.JCheckBox();
        btnFormaPagamento = new javax.swing.JButton();
        btnParcelamento = new javax.swing.JButton();
        btnDadosAdicionais = new javax.swing.JButton();
        btnContratar = new javax.swing.JButton();
        btnVerValores = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnEnviarPorEmail = new javax.swing.JButton();
        barraProgresso = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("NOVA COTAÇÃO");

        btnCadEnderecos.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCadEnderecos.setText("Endereços");
        btnCadEnderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEnderecosActionPerformed(evt);
            }
        });

        btnCadGpImpressora.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCadGpImpressora.setText("Escolher impressoras");
        btnCadGpImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadGpImpressoraActionPerformed(evt);
            }
        });

        btnCadServAdicionais.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCadServAdicionais.setText("Serviços adicionais");
        btnCadServAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadServAdicionaisActionPerformed(evt);
            }
        });

        jcbEndereco.setText("Endereço");
        jcbEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEnderecoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("CheckList");

        jcbGrupoImpressora.setText("Grupos De Impressoras");
        jcbGrupoImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGrupoImpressoraActionPerformed(evt);
            }
        });

        jcbServicosAdicionais.setText("Serviços adicionais");
        jcbServicosAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbServicosAdicionaisActionPerformed(evt);
            }
        });

        jbcFormaPagamento.setText("Forma de pagamento");
        jbcFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcFormaPagamentoActionPerformed(evt);
            }
        });

        jcbDadosPagamento.setText("Dados de pagamento");
        jcbDadosPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDadosPagamentoActionPerformed(evt);
            }
        });

        jcbParcelamento.setText("Parcelamento");
        jcbParcelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbParcelamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbDadosPagamento)
                        .addGap(18, 18, 18)
                        .addComponent(jcbParcelamento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(jcbGrupoImpressora)
                        .addGap(18, 18, 18)
                        .addComponent(jcbServicosAdicionais)
                        .addGap(18, 18, 18)
                        .addComponent(jbcFormaPagamento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEndereco)
                    .addComponent(jcbGrupoImpressora)
                    .addComponent(jcbServicosAdicionais)
                    .addComponent(jbcFormaPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDadosPagamento)
                    .addComponent(jcbParcelamento))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        btnFormaPagamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnFormaPagamento.setText("Forma de pagamento");
        btnFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormaPagamentoActionPerformed(evt);
            }
        });

        btnParcelamento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnParcelamento.setText("Parcelamento");
        btnParcelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcelamentoActionPerformed(evt);
            }
        });

        btnDadosAdicionais.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnDadosAdicionais.setText("Dados adicionais");
        btnDadosAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosAdicionaisActionPerformed(evt);
            }
        });

        btnContratar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnContratar.setText("CONTRATAR");

        btnVerValores.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnVerValores.setText("Valores e custos");

        btnImprimir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnImprimir.setText("IMPRIMIR");

        btnEnviarPorEmail.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnEnviarPorEmail.setText("Enviar por Email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCadGpImpressora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnParcelamento, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCadServAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDadosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVerValores)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviarPorEmail)
                        .addGap(18, 18, 18)
                        .addComponent(btnImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btnContratar)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadGpImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadServAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParcelamento, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDadosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContratar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarPorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerValores, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        barraProgresso.setToolTipText("");
        barraProgresso.setValue(18);

        jLabel2.setText("PROGESSO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barraProgresso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadEnderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEnderecosActionPerformed
        CreateEnderecoScreen dialog = new CreateEnderecoScreen(FrMain.getFrame(), false,this.cliente);
        dialog.setLocationRelativeTo(FrMain.getFrame());
        dialog.setSize(FrMain.getFrame().getSize());
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCadEnderecosActionPerformed

    private void btnCadGpImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadGpImpressoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadGpImpressoraActionPerformed

    private void btnCadServAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadServAdicionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadServAdicionaisActionPerformed

    private void jcbEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEnderecoActionPerformed

    private void jcbGrupoImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGrupoImpressoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGrupoImpressoraActionPerformed

    private void jcbServicosAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbServicosAdicionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbServicosAdicionaisActionPerformed

    private void jbcFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbcFormaPagamentoActionPerformed

    private void jcbParcelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbParcelamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbParcelamentoActionPerformed

    private void btnFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormaPagamentoActionPerformed

    private void btnParcelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcelamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParcelamentoActionPerformed

    private void jcbDadosPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDadosPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDadosPagamentoActionPerformed

    private void btnDadosAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosAdicionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDadosAdicionaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCotacaoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCotacaoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCotacaoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCotacaoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateCotacaoScreen dialog = new CreateCotacaoScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JButton btnCadEnderecos;
    private javax.swing.JButton btnCadGpImpressora;
    private javax.swing.JButton btnCadServAdicionais;
    private javax.swing.JButton btnContratar;
    private javax.swing.JButton btnDadosAdicionais;
    private javax.swing.JButton btnEnviarPorEmail;
    private javax.swing.JButton btnFormaPagamento;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnParcelamento;
    private javax.swing.JButton btnVerValores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jbcFormaPagamento;
    private javax.swing.JCheckBox jcbDadosPagamento;
    private javax.swing.JCheckBox jcbEndereco;
    private javax.swing.JCheckBox jcbGrupoImpressora;
    private javax.swing.JCheckBox jcbParcelamento;
    private javax.swing.JCheckBox jcbServicosAdicionais;
    // End of variables declaration//GEN-END:variables
}
